import { icons } from '$lib/utils/icons';

export const techIcons: Record<string, string> = {
	CSS: icons.css,
	'CSS3': icons.css,
	Express: icons.express,
	Framer: icons.framer,
	'Framer Motion': icons.framer,
	GSAP: icons.gsap,
	'Shadcn UI': icons.shadcn,
	'shadcn/ui': icons.shadcn,
	Git: icons.git,
	GitHub: icons.github,
	HTML: icons.html,
	'HTML5': icons.html,
	JavaScript: icons.javascript,
	JS: icons.javascript,
	MongoDB: icons.mongodb,
	mongo: icons.mongodb,
	'Next.js': icons.next,
	NextJS: icons.next,
	'Node.js': icons.node,
	NodeJS: icons.node,
	PostgreSQL: icons.postgresql,
	React: icons.react,
	'React Native': icons.react,
	Supabase: icons.supabase,
	Svelte: icons.svelte,
	SvelteKit: icons.svelte,
	'Tailwind CSS': icons.tailwind,
	TailwindCSS: icons.tailwind,
	TypeScript: icons.typescript,
	TS: icons.typescript,
	Vite: icons.vite,
	'Vue.js': icons.vue,
	Vue: icons.vue,
	'Chrome Web Store': icons.chrome,
};

export const techIconColors: Record<string, string> = {
	css: '#663399',
	express: '#000000',
	framer: '#0055FF',
	git: '#F05032',
	github: '#181717',
	gsap: '#0AE448',
	html: '#E34F26',
	javascript: '#F7DF1E',
	mongodb: '#47A248',
	next: '#000000',
	node: '#5FA04E',
	postgresql: '#4169E1',
	react: '#61DAFB',
	shadcn: '#000000',
	supabase: '#3FCF8E',
	svelte: '#FF3E00',
	tailwind: '#06B6D4',
	typescript: '#3178C6',
	vite: '#9135FF',
	vue: '#4FC08D',
	chrome: '#4285F4',
};

const labelToIconKey: Record<string, string> = {
	CSS: 'css',
	'CSS3': 'css',
	Express: 'express',
	Framer: 'framer',
	'Framer Motion': 'framer',
	GSAP: 'gsap',
	'Shadcn UI': 'shadcn',
	'shadcn/ui': 'shadcn',
	Git: 'git',
	GitHub: 'github',
	HTML: 'html',
	'HTML5': 'html',
	JavaScript: 'javascript',
	JS: 'javascript',
	MongoDB: 'mongodb',
	mongo: 'mongodb',
	'Next.js': 'next',
	NextJS: 'next',
	'Node.js': 'node',
	NodeJS: 'node',
	PostgreSQL: 'postgresql',
	React: 'react',
	'React Native': 'react',
	Supabase: 'supabase',
	Svelte: 'svelte',
	SvelteKit: 'svelte',
	'Tailwind CSS': 'tailwind',
	TailwindCSS: 'tailwind',
	TypeScript: 'typescript',
	TS: 'typescript',
	Vite: 'vite',
	'Vue.js': 'vue',
	Vue: 'vue',
	'Chrome Web Store': 'chrome',
};

export const getTechIconColor = (label: string): string | undefined =>
	techIconColors[labelToIconKey[label]];
